In [1]:
import pandas as pd

In [2]:
mark=pd.Series([90,50,6,80])

In [3]:
mark

0    90
1    50
2     6
3    80
dtype: int64

In [4]:
marks=pd.Series([90,50,80],index=["aman","vishal","chetan"])

In [5]:
marks

aman      90
vishal    50
chetan    80
dtype: int64

In [6]:
marks["aman"]

np.int64(90)

In [7]:
mark[0]

np.int64(90)

In [8]:
mark[2]

np.int64(6)

In [9]:
data={
    "name":["adil","abc","xyz","pqr"],
    "age":[19,20,25,22],
    "marks":[91,92,85,74],
    "roll":[8,15,1,7]
}
d=pd.DataFrame(data)
print(d)

   name  age  marks  roll
0  adil   19     91     8
1   abc   20     92    15
2   xyz   25     85     1
3   pqr   22     74     7

In [25]:
d.tail(2)

  name  age  marks  roll
2  xyz   25     85     1
3  pqr   22     74     7

In [43]:
d.to_csv("stud.csv",index=False)

In [44]:
df=pd.read_csv("stud.csv")

In [45]:
df

   name  age  marks  roll
0  adil   19     91     8
1   abc   20     92    15
2   xyz   25     85     1
3   pqr   22     74     7

In [ ]:
#NEW PROGRAM

In [29]:
a=[5,7,9]
b=[3,6,8]
c=[1,4,2]

In [37]:
ds=pd.DataFrame(columns=["x","y","z"])

In [38]:
ds

Empty DataFrame
Columns: [x, y, z]
Index: []

In [41]:
ds["x"]=a
ds["y"]=b
ds["z"]=c

In [42]:
ds

   x  y  z
0  5  3  1
1  7  6  4
2  9  8  2

In [ ]:
#NEW PROGRAM

In [48]:
ed=pd.read_csv("education.csv")

In [49]:
ed

     datasrno  workex  gmat
0           1      21   720
1           2     107   640
2           3      57   740
3           4      99   690
4           5     208   710
..        ...     ...   ...
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

[773 rows x 3 columns]

In [51]:
print(ed.tail())

     datasrno  workex  gmat
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

In [52]:
ed.tail(3)

     datasrno  workex  gmat
770       771      28   610
771       772      10   610
772       773      52   620

In [53]:
ed.head()

   datasrno  workex  gmat
0         1      21   720
1         2     107   640
2         3      57   740
3         4      99   690
4         5     208   710

In [54]:
ed.head(2)

   datasrno  workex  gmat
0         1      21   720
1         2     107   640

In [60]:
ed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datasrno  773 non-null    int64
 1   workex    773 non-null    int64
 2   gmat      773 non-null    int64
dtypes: int64(3)
memory usage: 18.2 KB

In [62]:
print()

In [64]:
ed.shape

(773, 3)

In [65]:
ed.columns

Index(['datasrno', 'workex', 'gmat'], dtype='object')

In [66]:
ed.dtypes

datasrno    int64
workex      int64
gmat        int64
dtype: object

In [67]:
ed.index

RangeIndex(start=0, stop=773, step=1)

In [68]:
ed.values

array([[  1,  21, 720],
       [  2, 107, 640],
       [  3,  57, 740],
       ...,
       [771,  28, 610],
       [772,  10, 610],
       [773,  52, 620]], shape=(773, 3))

In [69]:
ed.describe()

        datasrno     workex        gmat
count  773.00000  773.00000  773.000000
mean   387.00000   57.50194  711.164295
std    223.29017   27.38682   29.339714
min      1.00000    9.00000  600.000000
25%    194.00000   41.00000  690.000000
50%    387.00000   52.00000  710.000000
75%    580.00000   69.00000  730.000000
max    773.00000  279.00000  780.000000

In [71]:
ed.max()

datasrno    773
workex      279
gmat        780
dtype: int64

In [ ]:
# NEW PROGRAM

In [132]:
st={
    "Name":["abc","xyz","pqr","adil","mno","wxy","ijk","efg"],
    "marks":[65,85,65,90,52,34,48,98]
}

In [152]:
stu=pd.DataFrame(st)

In [155]:
stu.head(3)

  Name  marks
0  abc     65
1  xyz     85
2  pqr     65

In [156]:
stu.tail(2)

  Name  marks
6  ijk     48
7  efg     98

In [157]:
stu["Name"]

0     abc
1     xyz
2     pqr
3    adil
4     mno
5     wxy
6     ijk
7     efg
Name: Name, dtype: object

In [158]:
stu

   Name  marks
0   abc     65
1   xyz     85
2   pqr     65
3  adil     90
4   mno     52
5   wxy     34
6   ijk     48
7   efg     98

In [159]:
(stu["marks"].sum())/8

np.float64(67.125)

In [160]:
stu["marks"].max()

98

In [161]:
stu["marks"].min()

34

In [162]:
stu.loc[1]

Name     xyz
marks     85
Name: 1, dtype: object

In [163]:
stu.iloc[3]

Name     adil
marks      90
Name: 3, dtype: object

In [164]:
stu["age"]=[19,18,19,21,22,23,18,17]

In [165]:
stu

   Name  marks  age
0   abc     65   19
1   xyz     85   18
2   pqr     65   19
3  adil     90   21
4   mno     52   22
5   wxy     34   23
6   ijk     48   18
7   efg     98   17

In [166]:
stu[stu["marks"]>80]

   Name  marks  age
1   xyz     85   18
3  adil     90   21
7   efg     98   17

In [167]:
stu[(stu["marks"]>80) & (stu["age"]>20)]

   Name  marks  age
3  adil     90   21

In [168]:
stu.loc[3,"age"]=19

In [169]:
stu

   Name  marks  age
0   abc     65   19
1   xyz     85   18
2   pqr     65   19
3  adil     90   19
4   mno     52   22
5   wxy     34   23
6   ijk     48   18
7   efg     98   17

In [210]:
stu["age"].unique()

array([19, 18, 22, 23, 17])

In [ ]:
#NEW PROGRAM

In [203]:
emp={
    "name":["ABC","pqr","mno","xyz"],
    "dept":["cse","it","ece","AL"],
    "slry":[50000,120000,90000,100000],
    "exp":[2,5,3,4]
}

In [204]:
d=pd.DataFrame(emp)
d

  name dept    slry  exp
0  ABC  cse   50000    2
1  pqr   it  120000    5
2  mno  ece   90000    3
3  xyz   AL  100000    4

In [205]:
d[d["slry"]>50000]

  name dept    slry  exp
1  pqr   it  120000    5
2  mno  ece   90000    3
3  xyz   AL  100000    4

In [206]:
d.sort_values(by="slry",ascending=False)

  name dept    slry  exp
1  pqr   it  120000    5
3  xyz   AL  100000    4
2  mno  ece   90000    3
0  ABC  cse   50000    2

In [207]:
d["bonus"]=500
d

  name dept    slry  exp  bonus
0  ABC  cse   50000    2    500
1  pqr   it  120000    5    500
2  mno  ece   90000    3    500
3  xyz   AL  100000    4    500

In [208]:
d["final slry"]=d["slry"]*1.1
print(d)

  name dept    slry  exp  bonus  final slry
0  ABC  cse   50000    2    500     55000.0
1  pqr   it  120000    5    500    132000.0
2  mno  ece   90000    3    500     99000.0
3  xyz   AL  100000    4    500    110000.0

In [214]:
sales=pd.DataFrame({
    "Salesperson":["A","A","B","B","C","C"],
    "City":["Delhi","Lucknow","Delhi","Kanpur","Delhi","Lucknow"],
    "Product":["Pen","Book","Pen","Book","Book","Pen"],
    "Sales":[120,250,150,300,400,180]}
)
sales

  Salesperson     City Product  Sales
0           A    Delhi     Pen    120
1           A  Lucknow    Book    250
2           B    Delhi     Pen    150
3           B   Kanpur    Book    300
4           C    Delhi    Book    400
5           C  Lucknow     Pen    180

In [217]:
sales["Sales"].sum()

np.int64(1400)

In [218]:
sales.groupby("Salesperson")["Sales"].sum()

Salesperson
A    370
B    450
C    580
Name: Sales, dtype: int64

In [219]:
sales.groupby("City")["Sales"].sum()

City
Delhi      670
Kanpur     300
Lucknow    430
Name: Sales, dtype: int64

In [220]:
sales.pivot_table(values="Sales",index="City",columns="Product",aggfunc="sum")

Product   Book    Pen
City
Delhi    400.0  270.0
Kanpur   300.0    NaN
Lucknow  250.0  180.0